### PR TITLE
Add delay to fix race condition preventing panes from spawning.

### PR DESCRIPTION
**Pull request by jedis00**
Per https://github.com/bet4it/hyperinator/issues/2#issuecomment-621577535.

### CODE REVIEW

**Comment by bet4it** [comment]
I find a better way 😅
```diff
diff --git a/bin/hyperinator b/bin/hyperinator
index 29c0aef..ce06d12 100755
--- a/bin/hyperinator
+++ b/bin/hyperinator
@@ -63,7 +63,9 @@ function start() {
         console.error(err)
         return
       }
-      console.log(`[hyperinator config: ${cfgPath}]`)
+      setTimeout(() => {
+        console.log(`[hyperinator config: ${cfgPath}]`)
+      }, 100)
       break
     default:
       console.error('Unknown command!')
```

**Comment by jedis00** [comment]
Seems to work fine! Closing this one.

**Comment by jedis00** [comment]
@bet4it ```git diff``` appears to break Hyper with this patch. I can't press ```q``` to exit out of the diff. It hangs. No other combo of ```CTRL+C```, ```CTRL+Z``` seem to work. Have to kill bash. It works fine with Git Bash itself, just Hyper is effected.

**Comment by bet4it** [comment]
Could you confirm that all the problems you faced have been fixed in the latest release?

**Comment by jedis00** [comment]
@bet4it No. git diff is still broken. When scrolling a multi-line diff, you cannot exit out of it by pressing ```q```. The pane is frozen and the bash process needs to be killed.

**Comment by bet4it** [comment]
Can't reproduce, again😅
But this should happen only when you read hyperinator's code, which is quite uncommon for most people. Let's just ignore it😃

**Comment by jedis00** [comment]
No, it’s an issue with any git repo. I wasn’t doing a diff in hyperinator but something for work. The git diff command is completely broken in Hyper with this patch. Still works fine in a regular git bash shell.

**Comment by bet4it** [comment]
```diff
diff --git a/bin/hyperinator b/bin/hyperinator
index 29c0aef..ce06d12 100755
--- a/bin/hyperinator
+++ b/bin/hyperinator
@@ -63,7 +63,9 @@ function start() {
         console.error(err)
         return
       }
-      console.log(`[hyperinator config: ${cfgPath}]`)
+      setTimeout(() => {
+        console.log(`[hyperinator config: ${cfgPath}]`)
+      }, 100)
       break
     default:
       console.error('Unknown command!')
```
Do you mean this patch introduce the bug? That's impossible! This patch doesn't change anything if you don't use `hyperinator`. This bug must exist in prior version.
So this bug happens even you don't use `hyperinator` to create the layout? Could you help me figure out which version introduce this bug?

**Comment by bet4it** [comment]
Is this a bug of other plugins? You may add other plugins back recently.

**Comment by jedis00** [comment]
I’m not sure if it was specifically that patch or another we tried.

I did add hyperpane back because I liked having the label in the top left corner of the pane that showed the keyboard shortcut to use to swap to that active pane.

**Comment by bet4it** [comment]
Yeah, hyper-pane is very useful and I also use it. I don't think it's the culprit.
Hope for more information.

**Pull request closed without merging**
